21name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Run tests with Gradle
        run: ./gradlew test
